---
title: "Exam 2"
format: html
---

```{r}
#| label: Initialize project
#| warning: false
library(tidyverse)
library(tidytuesdayR)
```

```{r}
tuesdata <- tt_load('2020-02-18')
fc <- tuesdata$food_consumption
```


```{r}
fcc <- fc |>
  mutate(food_category = fct_recode(food_category,
                                    "Lamb"= "Lamb & Goat",
                                    "Dairy" = "Milk - inc. cheese",
                                    "Wheat" = "Wheat and Wheat Products",
                                    "Nuts" = "Nuts inc. Peanut Butter"))

fcc |>
  distinct(food_category)
```


## Question 1: Which 5 countries consume the most food?

```{r}
fcc |>
  group_by(country) |>
  summarise(total_consumption = sum(consumption)) |>
  arrange(desc(total_consumption)) |>
  head(5)
```
```{r}
fcc |>
  group_by(country) |>
  summarise(total_consumption = sum(consumption)) |>
  arrange(desc(total_consumption)) |>
  head(5) |>
  ggplot(aes(x = country, y = total_consumption)) +
  geom_col()
```

## Question 2: Which 5 countries consume the most of each food?

```{r}
fcc |>
  select(-co2_emmission) |>
  group_by(food_category) |>
  slice_max(n = 5, order_by = consumption)
```

```{r}
fcc |>
  select(-co2_emmission) |>
  group_by(food_category) |>
  slice_max(n = 5, order_by = consumption) |>
  ggplot(aes(x = country, y = consumption)) +
  geom_col() +
  facet_wrap(~food_category)
```

## Question 3: What does the consumption of each food look like across the world?

```{r}
library(rnaturalearth)
library(mosaic)
```

```{r}
library(viridisLite)
```

```{r}
#| fig-alt: A graph showing eleven world maps. Each map is labelled with a different food group. The map is colored based on how much of each food group is consumed by citizens of a given country consume food from the corresponding food group.
#| fig-cap: A series of world maps. The color of each country is determined by the normalized rate at which it consumes a certain food group (kg/person/year). Each map depicts consumption rates for a different food group.

world_boundaries = ne_countries(returnclass = "sf")

world_boundaries |>
  select(name, geometry) |>
  mutate(name = ifelse(name == "United States of America", "USA", name)) |>
  mutate(name = ifelse(name == "Bosnia and Herz.", "Bosnia and Herzegovina", name)) |>
  mutate(name = ifelse(name == "Czechia", "Czech Republic", name)) |>
  mutate(name = ifelse(name == "Taiwan", "Taiwan. ROC", name)) |>
  left_join(
    fcc |> 
      select(-co2_emmission) |>
      group_by(food_category) |>
      mutate(consumption = (consumption - mean(consumption))/sd(consumption)),
    join_by(name == country)) |>
  pivot_wider(names_from = food_category, values_from = consumption) |>
  select(-"NA") |>
  pivot_longer(cols = c(-name, -geometry),
               names_to = "food_category",
               values_to = "consumption") |>
  ggplot() +
  geom_sf(aes(fill = consumption)) +
  facet_wrap(~food_category) +
  scale_fill_viridis_c("Consumption level") +
  labs(title = "Food consumption across the world") +
  theme(legend.position = "bottom")

```

