---
title: "Spatial Viz"
---

Use this file to generate a professional looking **spatial** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.
<<<<<<< HEAD

```{r}
#| label: Initialize project
#| warning: false
library(tidyverse)
library(tidytuesdayR)
library(viridisLite)
library(leaflet)
library(gplots)

tuesdata <- tidytuesdayR::tt_load(2023, week = 25)

ufo_sightings <- tuesdata$`ufo_sightings`
places <- tuesdata$`places`
day_parts_map <- tuesdata$`day_parts_map`

```

```{r}
#| warning: false
library(mosaic)
library(rnaturalearth)
world_boundaries <- ne_countries(returnclass = "sf")
```


```{r}
#|fig-cap: "Global distribution of UFO sightings reported to the National UFO Reporting Center. Data source: https://github.com/rfordatascience/tidytuesday/blob/main/data/2023/2023-06-20/readme.md."
#|fig-alt: "A map showing the distribution of UFO sightings reported to the National UFO Reporting Center. The majority of reported sightings came from the United States, Western Europe, and Australia."

ggplot(world_boundaries) + 
  geom_sf() + 
  geom_point(
    data = places,
    aes(x = longitude, y = latitude),
    alpha = 0.3, size = 0.2, color = "darkred"
  ) +
  labs(title = "UFO sightings reported to the National UFO Reporting Center") +
  theme_map()

```

=======
>>>>>>> parent of 5bfbfab (Quadvariate viz implemented.)
